providers = ["node", "python"]

[phases.setup]
nixPkgs = ["...", "yarn"]

[phases.install]
cmds = [
  "cd server && python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt",
  "cd client && yarn install"
]

[phases.build]
cmds = ["...", "cd client && yarn build"]

[start]
cmd = "cd server && python warwomb/main.py"
