providers = ["node", "python"]

[phases.setup]
nixPkgs = ["...", "yarn", "poetry"]

[phases.install]
cmds = [
  "cd server && poetry shell && poetry install",
  "cd client && yarn install"
]

[phases.build]
cmds = ["...", "cd client && yarn build"]

[start]
cmd = "cd server && poetry shell && poetry run start"
