"""make energy types many-to-many

Revision ID: 3016f45e7878
Revises: 88e62f416acf
Create Date: 2023-04-07 23:48:06.150987

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '3016f45e7878'
down_revision = '88e62f416acf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weapon_energy_type_link',
    sa.Column('weapon_id', sa.Integer(), nullable=False),
    sa.Column('energy_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['energy_type_id'], ['weapon_energy_types.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['unit_weapons.id'], ),
    sa.PrimaryKeyConstraint('weapon_id', 'energy_type_id')
    )
    op.drop_constraint('unit_weapons_energy_type_id_fkey', 'unit_weapons', type_='foreignkey')
    op.drop_column('unit_weapons', 'energy_type_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('unit_weapons', sa.Column('energy_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('unit_weapons_energy_type_id_fkey', 'unit_weapons', 'weapon_energy_types', ['energy_type_id'], ['id'])
    op.drop_table('weapon_energy_type_link')
    # ### end Alembic commands ###
