"""add description to weapon quality

Revision ID: 88e62f416acf
Revises: 6995f4b86457
Create Date: 2023-04-07 22:24:30.352703

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '88e62f416acf'
down_revision = '6995f4b86457'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weapon_qualities', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weapon_qualities', 'description')
    # ### end Alembic commands ###
