"""added user and role models

Revision ID: f1e356c13464
Revises: 9195f2137a84
Create Date: 2023-04-08 03:58:09.330112

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f1e356c13464'
down_revision = '9195f2137a84'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('unit_advantage_links',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_advantange_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_advantange_id'], ['unit_advantages.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('unit_id', 'unit_advantange_id')
    )
    op.create_table('user',
    sa.Column('auth_provider', sa.Enum('Google', name='authprovider'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('unit_weapon_links',
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('unit_weapon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.ForeignKeyConstraint(['unit_weapon_id'], ['unit_weapons.id'], ),
    sa.PrimaryKeyConstraint('unit_id', 'unit_weapon_id')
    )
    op.create_table('weapon_energy_type_links',
    sa.Column('weapon_id', sa.Integer(), nullable=False),
    sa.Column('energy_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['energy_type_id'], ['weapon_energy_types.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['unit_weapons.id'], ),
    sa.PrimaryKeyConstraint('weapon_id', 'energy_type_id')
    )
    op.drop_table('weapon_energy_type_link')
    op.drop_table('unit_weapon_link')
    op.drop_table('unit_advantage_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit_advantage_link',
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_advantange_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['unit_advantange_id'], ['unit_advantages.id'], name='unit_advantage_link_unit_advantange_id_fkey'),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name='unit_advantage_link_unit_id_fkey'),
    sa.PrimaryKeyConstraint('unit_id', 'unit_advantange_id', name='unit_advantage_link_pkey')
    )
    op.create_table('unit_weapon_link',
    sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_weapon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], name='unit_weapon_link_unit_id_fkey'),
    sa.ForeignKeyConstraint(['unit_weapon_id'], ['unit_weapons.id'], name='unit_weapon_link_unit_weapon_id_fkey'),
    sa.PrimaryKeyConstraint('unit_id', 'unit_weapon_id', name='unit_weapon_link_pkey')
    )
    op.create_table('weapon_energy_type_link',
    sa.Column('weapon_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('energy_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['energy_type_id'], ['weapon_energy_types.id'], name='weapon_energy_type_link_energy_type_id_fkey'),
    sa.ForeignKeyConstraint(['weapon_id'], ['unit_weapons.id'], name='weapon_energy_type_link_weapon_id_fkey'),
    sa.PrimaryKeyConstraint('weapon_id', 'energy_type_id', name='weapon_energy_type_link_pkey')
    )
    op.drop_table('weapon_energy_type_links')
    op.drop_table('unit_weapon_links')
    op.drop_table('user')
    op.drop_table('unit_advantage_links')
    op.drop_table('roles')
    # ### end Alembic commands ###
